### PR TITLE
fix whitespace in output file

### LINKED ISSUE #4: Output file with spaces in variable
If I have a %VAR_name% like "test, foo" and I want to use this as output file via -d %VAR_name%.pdf I do get an error as only the first part (till the space) is being used.

Thank you for this great script!

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
fix #4

### CODE REVIEW

**Comment by borgand** [comment]
Thanks for the fix

**Comment by tobiasKaminsky** [comment]
Always happy to help :+1: 
As I do not know ruby gems very well: will this fix be included immediately? Or is there some kind of versioning in gems?

**Comment by borgand** [comment]
No, I'll have to rebuild the gem and upload it to take effect. Will do that soon.

**Comment by borgand** [comment]
OK, now I released `v 0.2.0` and published it to Rubygems. Please test it and see if it works.

**Pull request merged**
